"""Established one-to-many relationship.

Revision ID: 098a522049f8
Revises: 0fb820fe1ceb
Create Date: 2023-05-06 23:04:48.079742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098a522049f8'
down_revision = '0fb820fe1ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_table('authors')
    # ### end Alembic commands ###
