"""Dropped author column.

Revision ID: 0fb820fe1ceb
Revises: 7500cdab1e52
Create Date: 2023-05-06 20:13:05.599263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb820fe1ceb'
down_revision = '7500cdab1e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
